trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

variables:
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}:
    PKGVER: ${{ variables['Build.SourceBranchName'] }}
  ${{ if not(startsWith(variables['Build.SourceBranch'], 'refs/tags/')) }}:
    PKGVER: '0.0.0-dev'

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'

pool:
  vmImage: $(imageName)

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
    includePreviewVersions: true

- task: Bash@3
  inputs:
    filePath: fake.sh
    arguments: run
  env:
    GITHUB_TOKEN: $(GITHUB_TOKEN)
